Add data to API
MT-CTF/server_stats pull request #1
Opened 2023-05-17 20:49 UTC by FlamingRCCars

I added a list of connected players to the API, its confirmed working on a local server.

Attached below is a picture of the resulting .json.

![confirmed_working](https://github.com/MT-CTF/server_stats/assets/106501309/7f29dad8-5ebf-434f-b546-73728b903e83)

2023-05-17 22:53 UTC, LoneWolfHT requested changes
My suggestions will get you started on the proper implementation

2023-05-17 22:53 UTC, LoneWolfHT commented on init.lua
> +end
```suggestion
local function get_player_list()
	local player_names = {}

	for _, player in ipairs(minetest.get_connected_players()) do
    	table.insert(player_names, player:get_player_name())
	end

	return player_names, #player_names
end
```

2023-05-17 22:53 UTC, LoneWolfHT commented on init.lua
> +local start_time_map = ''
```suggestion
local cache = {}
```

2023-05-17 22:53 UTC, LoneWolfHT commented on init.lua
> +
```suggestion
```

2023-05-17 22:54 UTC, FlamingRCCars commented on init.lua
> +local start_time_map = ''
I thought there was a better way, just plumb slipped my mind.

2023-05-17 22:54 UTC, LoneWolfHT commented on init.lua
> +
Basically just revert the changes you made when adding these variables

2023-05-17 23:03 UTC, FlamingRCCars commented
Changes pushed, confirmed working: 
![image](https://github.com/MT-CTF/server_stats/assets/106501309/9000d6e0-86d9-4b02-b986-50e8b7c59046)

2023-05-18 00:19 UTC, LoneWolfHT commented on init.lua
> +		})
```suggestion
        cache.player_info = {
             players = player_names,
             count = player_count
        }
        update(cache)
```

2023-05-18 00:20 UTC, LoneWolfHT commented
For some reason my fourth suggestion didn't appear, see my latest one on how to use the `cache` var

2023-05-18 01:45 UTC, FlamingRCCars commented
Made changes based of of @LoneWolfHT's suggestions, and stopped using globalstep() in favor of joinplayer/leaveplayer.

Confirmed working:

![image](https://github.com/MT-CTF/server_stats/assets/106501309/53873d1f-b680-4ca4-9dad-f333d3f5ee29)

2023-05-18 02:58 UTC, LoneWolfHT approved these changes

2023-05-18 02:58 UTC, merged